language: go

services:
- docker

before_install:
- docker build -t code-camp-2019 .

deploy:
  provider: heroku
  api_key:
    secure: "3bYaIecBGYs65OmSiBbc5UgBNpVjwiwfSTV4/MIUYFtP81XPWwN/rq7pZpd2VvZLrH6Ny65tYVZVgF/FFLPgza7ghVUTovRVwC7gfi4Cqj6eATfj72L4hZFEuSvGKsXVsNXWVyMETBHXlYhjzFnSwbtwYdUvRazgRMxCg/f/qZvt8fDDdGIQZlvcS601L0fuyUITqGm5f5J1LKJpFkG3BZzPogn9pxNu4utYiz2c3Dc8+aqliWRoAvtsfSaDPcxC7eiy8aOQ0fGefBkVtvlOxuo2sn2AyQdqMEwFTkAOoIoKWZLeSU5E7zfX5zm6RCgzvabV5TGJlVSwYg665EfXlVUKZv8cAJIlKC+89M36cMzbPunISlfb64YFVm+a77a4CbNQBHJtnQi8R6Bp3iTc0vU4GbqNgSkwf2ypS4u9PlaukS1e1cSwmI+Eq25mn5OGmQ4gINjr14LUcXAygMfzrceTyoTMQDkhFWR7/9okeZKKzMA7dkpE25RTYYQLW5o+D/p0o3f8+UyyMJUTM1IGSzBVzbDiaKxOT6288f1RjYgz4MLicr7jR0W9dNUHMOkYviRRJfecgY4Cp2BqeDL9uLwOjTpPxULXUPSZ8FiN2lDKnQmDujY0YxcEqSmoHE3PKr9cekL6DArIWCFArYz0mkHRCn6FulqGijdQNcT/OiA="
